version: "3.8"
services:
#  nexus:
#    container_name: nexus
#    image: sonatype/nexus3
#    ports:
#    - target: 8081
#      published: 8081
      
  central_app:
    container_name: service1
    image: localhost:8082/service1_image
    build: ./service-1
    ports:
    - target: 5000
      published: 5000
      
  random_num:
    container_name: service2
    image: localhost:8082/service2_image
    build: ./service-2
    
  random_lett:
    container_name: service3
    image: localhost:8082/service3_image
    build: ./service-3
    
  account_num:
    container_name: service4
    image: localhost:8082/service4_image
    build: ./service-4
    ports:
      - target: 5001
        published: 5001
  
  sonarqube:
    container_name: sonarqube
    image: sonarqube
    ports:
    - target: 9000
      published: 9000
