- hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
  - name: 'Install Required Dependencies'
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - git
      update_cache: yes
  
  - name: 'Add Docker Apt Key'
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: 'Add Docker Apt Repository'
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: 'Install Docker CE'
    apt:
      name: docker-ce
      update_cache: yes

  - name: 'Install Python Package Docker'
    pip:
      name: docker

  - name: 'Start Docker Service'
    service:
      name: docker
      state: started
